services:
  # PostgreSQL with pgvector for CoachNTT development
  coachntt-postgres-dev:
    image: pgvector/pgvector:pg16
    container_name: coachntt-postgres-dev
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=coachntt_cognitive_dev
      - POSTGRES_USER=coachntt_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coachntt_dev_pass}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coachntt_user -d coachntt_cognitive_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coachntt-dev-network
    labels:
      - "environment=DEVELOPMENT"
      - "purpose=coachntt-cognitive-testing"

  coachntt-chromadb-dev:
    image: chromadb/chroma:latest
    container_name: coachntt-chromadb-dev
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma-coachntt-dev:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coachntt-dev-network
    labels:
      - "environment=DEVELOPMENT"
      - "purpose=coachntt-memory-testing"

networks:
  coachntt-dev-network:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local

# Development-specific secrets (if needed)
secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  github_access_token:
    file: ./secrets/github_access_token.txt