services:
  # PostgreSQL with pgvector for CoachNTT Cognitive Platform
  coachntt-postgres:
    image: pgvector/pgvector:pg16
    container_name: coachntt-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coachntt_cognitive_db
      - POSTGRES_USER=coachntt_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coachntt_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coachntt_user -d coachntt_cognitive_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coachntt-platform-network

  coachntt-chromadb:
    image: chromadb/chroma:latest
    container_name: coachntt-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coachntt-platform-network

  # CoachNTT Cognitive Server - For development/testing only
  # Claude Desktop creates its own container (coachntt-cognitive-server)
  # Uncomment below to test the MCP server independently
  
  # coachntt-cognitive:
  #   build: .
  #   container_name: coachntt-cognitive-server
  #   restart: "no"
  #   depends_on:
  #     - coachntt-chromadb
  #     - coachntt-postgres
  #   environment:
  #     - DOCKER_CONTAINER=true
  #     - CHROMA_HOST=coachntt-chromadb
  #     - CHROMA_PORT=8000
  #     - MEMORY_IMPORTANCE_THRESHOLD=${MEMORY_IMPORTANCE_THRESHOLD:-0.7}
  #     - MEMORY_COLLECTION_NAME=${MEMORY_COLLECTION_NAME:-ai_memories}
  #     - MAX_MEMORY_RESULTS=${MAX_MEMORY_RESULTS:-10}
  #     - MCP_SERVER_NAME=${MCP_SERVER_NAME:-ai-memory-server}
  #     - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
  #   secrets:
  #     - openai_api_key
  #     - github_access_token
  #   volumes:
  #     - ./data/memories:/app/data
  #     - ./Project_Context/vault:/vault:rw
  #   networks:
  #     - memory-network
  #   command: ["node", "dist/index.js"]

networks:
  coachntt-platform-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  github_access_token:
    file: ./secrets/github_access_token.txt