# CoachNTT Development Environment - Complete development stack with voice features
# Usage: docker-compose -f docker-compose.yml -f docker-compose.coachntt.yml up -d
#
# This adds the CoachNTT cognitive server to the base infrastructure for local development.
# Voice features can be enabled via environment variables.

services:
  # CoachNTT Cognitive Server - Main development server
  coachntt-cognitive:
    build: .
    container_name: coachntt-cognitive-server
    restart: "no"
    depends_on:
      - coachntt-chromadb
      - coachntt-postgres
    environment:
      # Core Configuration
      - DOCKER_CONTAINER=true
      - CHROMA_HOST=coachntt-chromadb
      - CHROMA_PORT=8000
      - POSTGRES_HOST=coachntt-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-coachntt_cognitive_db}
      - POSTGRES_USER=${POSTGRES_USER:-coachntt_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coachntt_pass}
      
      # Memory Configuration
      - MEMORY_IMPORTANCE_THRESHOLD=${MEMORY_IMPORTANCE_THRESHOLD:-0.7}
      - MEMORY_COLLECTION_NAME=${MEMORY_COLLECTION_NAME:-coachntt_memories}
      - MAX_MEMORY_RESULTS=${MAX_MEMORY_RESULTS:-10}
      
      # Server Configuration
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-coachntt-cognitive-server}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-2.1.0}
      
      # Platform Features
      - USE_HYBRID_STORAGE=${USE_HYBRID_STORAGE:-true}
      - CODE_INDEXING_ENABLED=${CODE_INDEXING_ENABLED:-true}
      
      # Session Logging
      - AUTO_START_SESSION_LOGGING=${AUTO_START_SESSION_LOGGING:-true}
      - SESSION_LOGGING_PROJECT_NAME=${SESSION_LOGGING_PROJECT_NAME:-CoachNTT Cognitive Platform}
      - SESSION_LOGGING_SAVE_ON_EXIT=${SESSION_LOGGING_SAVE_ON_EXIT:-true}
      
      # Voice Features (optional)
      - COACHNTT_VOICE_ENABLED=${COACHNTT_VOICE_ENABLED:-false}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_DEFAULT_VOICE=${ELEVENLABS_DEFAULT_VOICE:-EXAVITQu4vr4xnSDxMaL}
      - ELEVENLABS_MODEL=${ELEVENLABS_MODEL:-eleven_monolingual_v1}
      
      # Dual Vault Configuration
      - VAULT_MODE=${VAULT_MODE:-dual}
      - CORE_VAULT_PATH=/core-vault
      - PROJECT_VAULT_PATH=/project-vault
      - OBSIDIAN_VAULT_PATH=/project-vault
      
    secrets:
      - openai_api_key
      - github_access_token
      
    volumes:
      - ./data/memories:/app/data
      - ${CORE_VAULT_HOST_PATH:-C:/Users/Steve/Obsidian/StevesVault}:/core-vault:rw
      - ${PROJECT_VAULT_HOST_PATH:-./vault}:/project-vault:rw
      
    networks:
      - coachntt-platform-network
      
    command: ["node", "dist/index.js"]
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

# Note: Base infrastructure (postgres, chromadb) is defined in docker-compose.yml
# This overlay adds the development server with all CoachNTT features