services:
  # PostgreSQL with pgvector for CoachNTT Voice Features
  coachntt-postgres-voice:
    image: pgvector/pgvector:pg16
    container_name: coachntt-postgres-voice
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    environment:
      - POSTGRES_DB=coachntt_voice_db
      - POSTGRES_USER=coachntt_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coachntt_pass}
    volumes:
      - postgres_coachntt_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coachntt_user -d coachntt_voice_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coachntt-voice-network

  coachntt-chromadb-voice:
    image: chromadb/chroma:latest
    container_name: coachntt-chromadb-voice
    ports:
      - "8002:8000"  # Different port to avoid conflicts
    volumes:
      - ./data/chroma-coachntt-voice:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - coachntt-voice-network

  # CoachNTT Voice Server (specialized for audio features)
  coachntt-voice:
    build:
      context: .
      dockerfile: Dockerfile.coachntt
    container_name: coachntt-voice-server
    depends_on:
      - coachntt-chromadb-voice
      - coachntt-postgres-voice
    environment:
      - DOCKER_CONTAINER=true
      - CHROMA_HOST=coachntt-chromadb-voice
      - CHROMA_PORT=8000
      - POSTGRES_HOST=coachntt-postgres-voice
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=coachntt_voice_db
      - POSTGRES_USER=coachntt_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-coachntt_pass}
      - USE_HYBRID_STORAGE=true
      - CODE_INDEXING_ENABLED=true
      - MCP_SERVER_NAME=CoachNTT
      - MCP_SERVER_VERSION=1.0.0
    secrets:
      - openai_api_key
    volumes:
      - ./data/coachntt:/app/data
    networks:
      - coachntt-voice-network
    command: ["node", "dist/index-coachntt.js"]

networks:
  coachntt-voice-network:
    driver: bridge

volumes:
  postgres_coachntt_data:
    driver: local

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt